### ISSUE TITLE
How can I have IPMITool for Esxi 6.5

### ISSUE THREAD

**Issue by dungla2011** [ewen-naos-nz/docker-build-static-ipmitool#1]
Thank  you much!

**Comment by ewenmcneill** [comment]
You need to [use Docker](https://docs.docker.com/install/) to build the `ipmitool` yourself.   There are [instructions in the `README` file](https://github.com/ewenmcneill/docker-build-static-ipmitool/blob/master/README.md).   It relies on a very old Docker base image (https://github.com/blalor/docker-centos4-base) which has been archived, but still seems to exist.  So maybe it is still possible to build it.

I have only tested the resulting `ipmitool` binary with ESXi 4.x, 5.0 and 6.0.  But since it is statically linked there is a good chance it would work with ESXi 6.5.

Sorry, I am unable to provide any further support for building this binary using Docker, as I have not used it myself in several years.

Ewen
